#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v26
# autospec commit: 99a7985
#
Name     : salt
Version  : 3007.2
Release  : 44
URL      : https://github.com/saltstack/salt/archive/v3007.2/salt-3007.2.tar.gz
Source0  : https://github.com/saltstack/salt/archive/v3007.2/salt-3007.2.tar.gz
Summary  : Portable, distributed, remote execution and configuration management system
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: salt-bin = %{version}-%{release}
Requires: salt-license = %{version}-%{release}
Requires: salt-man = %{version}-%{release}
Requires: salt-python = %{version}-%{release}
Requires: salt-python3 = %{version}-%{release}
Requires: pypi(pycryptodomex)
BuildRequires : buildreq-distutils3
BuildRequires : pypi-distro
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
salt-api is a modular interface on top of Salt that can provide a variety of entry points into a running Salt system.

%package bin
Summary: bin components for the salt package.
Group: Binaries
Requires: salt-license = %{version}-%{release}

%description bin
bin components for the salt package.


%package license
Summary: license components for the salt package.
Group: Default

%description license
license components for the salt package.


%package man
Summary: man components for the salt package.
Group: Default

%description man
man components for the salt package.


%package python
Summary: python components for the salt package.
Group: Default
Requires: salt-python3 = %{version}-%{release}

%description python
python components for the salt package.


%package python3
Summary: python3 components for the salt package.
Group: Default
Requires: python3-core
Provides: pypi(salt)
Requires: pypi(contextvars)
Requires: pypi(distro)
Requires: pypi(jinja2)
Requires: pypi(jmespath)
Requires: pypi(markupsafe)
Requires: pypi(msgpack)
Requires: pypi(psutil)
Requires: pypi(pyyaml)
Requires: pypi(pyzmq)
Requires: pypi(requests)

%description python3
python3 components for the salt package.


%prep
%setup -q -n salt-3007.2
cd %{_builddir}/salt-3007.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1747252196
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . pyzmq
python3 -m build --wheel --skip-dependency-check --no-isolation


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/salt
cp %{_builddir}/salt-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/salt/372cceb117b31a95566c62764361fd483c1aabf4 || :
cp %{_builddir}/salt-%{version}/NOTICE %{buildroot}/usr/share/package-licenses/salt/968c955ad2cce5856b6f723e7e70a283df0ea8e7 || :
cp %{_builddir}/salt-%{version}/pkg/debian/copyright %{buildroot}/usr/share/package-licenses/salt/9200e18c310756c3dee22cc63d9772ca50027489 || :
cp %{_builddir}/salt-%{version}/pkg/macos/pkg-resources/license.rtf %{buildroot}/usr/share/package-licenses/salt/94a0b2b7dd428eac792039f59a9deed5216c0192 || :
cp %{_builddir}/salt-%{version}/pkg/windows/msi/pkg_resources/LICENSE.rtf %{buildroot}/usr/share/package-licenses/salt/4872bfc8b78a1538422032c6fcc7c18ef034d9a6 || :
cp %{_builddir}/salt-%{version}/pkg/windows/nsis/installer/LICENSE.txt %{buildroot}/usr/share/package-licenses/salt/83c34cc83115e5f513e2cde030e2d64c589447a2 || :
cp %{_builddir}/salt-%{version}/tests/pytests/unit/modules/sol10_pkg/bashs/SUNWbashS/install/copyright %{buildroot}/usr/share/package-licenses/salt/869dfc8f2ae39a287e88ffca20966beab5b08ab8 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
pypi-dep-fix.py %{buildroot} pyzmq
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/salt
/usr/bin/salt-api
/usr/bin/salt-call
/usr/bin/salt-cloud
/usr/bin/salt-cp
/usr/bin/salt-key
/usr/bin/salt-master
/usr/bin/salt-minion
/usr/bin/salt-pip
/usr/bin/salt-proxy
/usr/bin/salt-run
/usr/bin/salt-ssh
/usr/bin/salt-syndic
/usr/bin/spm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/salt/372cceb117b31a95566c62764361fd483c1aabf4
/usr/share/package-licenses/salt/4872bfc8b78a1538422032c6fcc7c18ef034d9a6
/usr/share/package-licenses/salt/83c34cc83115e5f513e2cde030e2d64c589447a2
/usr/share/package-licenses/salt/869dfc8f2ae39a287e88ffca20966beab5b08ab8
/usr/share/package-licenses/salt/9200e18c310756c3dee22cc63d9772ca50027489
/usr/share/package-licenses/salt/94a0b2b7dd428eac792039f59a9deed5216c0192
/usr/share/package-licenses/salt/968c955ad2cce5856b6f723e7e70a283df0ea8e7

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/salt-api.1
/usr/share/man/man1/salt-call.1
/usr/share/man/man1/salt-cloud.1
/usr/share/man/man1/salt-cp.1
/usr/share/man/man1/salt-key.1
/usr/share/man/man1/salt-master.1
/usr/share/man/man1/salt-minion.1
/usr/share/man/man1/salt-proxy.1
/usr/share/man/man1/salt-run.1
/usr/share/man/man1/salt-ssh.1
/usr/share/man/man1/salt-syndic.1
/usr/share/man/man1/salt.1
/usr/share/man/man1/spm.1
/usr/share/man/man7/salt.7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
